name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Compile with gcc
        run: gcc projectTemplate.c -o projectTemplate.exe

      - name: Run
        run: ./projectTemplate.exe
