name: Release

on:
  release:
    types: [ created ]

permissions:
  contents: write

jobs:
  build-and-attach:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Compile with gcc
        run: gcc projectTemplate.c -o projectTemplate.exe

      - name: Upload binary to release
        uses: softprops/action-gh-release@v2
        with:
          files: projectTemplate.exe
